services:
  push-sub:
    image: quay.io/bitrix24/push:${PUSH_VERSION}
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=
      - PUSH_SECURITY_KEY=${PUSH_SECURITY_KEY}
      - PUSH_SUB_MODE=${PUSH_SUB_MODE}
      - PUSH_SUB_PORT=${PUSH_SUB_PORT}
      - COMPOSE_PROJECT_NAME=dev
    networks:
      - traefik-shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.push-sub.rule=Host(`push-sub.localhost`)
      - traefik.http.routers.push-sub.entrypoints=http
      - traefik.http.services.push-sub.loadbalancer.server.port=${PUSH_SUB_PORT}
    init: true
    cgroup: private
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    depends_on:
      - redis

  push-pub:
    image: quay.io/bitrix24/push:${PUSH_VERSION}
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=
      - PUSH_SECURITY_KEY=${PUSH_SECURITY_KEY}
      - PUSH_PUB_MODE=${PUSH_PUB_MODE}
      - PUSH_PUB_PORT=${PUSH_PUB_PORT}
      - COMPOSE_PROJECT_NAME=dev
    networks:
      - traefik-shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.push-pub.rule=Host(`push-pub.localhost`)
      - traefik.http.routers.push-pub.entrypoints=http
      - traefik.http.services.push-pub.loadbalancer.server.port=${PUSH_PUB_PORT}
    init: true
    cgroup: private
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    depends_on:
      - redis

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    restart: unless-stopped
    networks:
      - traefik-shared
    command: ["redis-server", "--appendonly", "yes"]
    init: true
    cgroup: private
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid

  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-shared"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    restart: always
    networks:
      - traefik-shared
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  traefik-shared:
    name: traefik-shared
    driver: bridge
